language: python

python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"

sudo: false

before_install:
  - if [ "$TRAVIS_PULL_REQUEST" != "false" ] && [ "$TRAVIS_BRANCH" == "master" ]; then
      echo "No pull requests can be sent to the master branch" 1>&2;
      exit 1;
    fi
  - pip install codecov
install:
  - python scripts/ci/install
script: python scripts/ci/run-tests
after_success:
  - rm tests/coverage.xml && mv tests/.coverage ./ && codecov
